#!/bin/bash

# Script hướng dẫn triển khai các phương pháp kết nối Kafka với MongoDB
echo "=== HƯỚNG DẪN TRIỂN KHAI CÁC PHƯƠNG PHÁP KẾT NỐI KAFKA VỚI MONGODB ==="
echo ""

# Phần 1: Khởi động các dịch vụ
echo "=== PHẦN 1: KHỞI ĐỘNG CÁC DỊCH VỤ ==="
echo "Khởi động các container với docker-compose..."
echo "Lệnh: docker-compose up -d"
echo ""
echo "Chờ các dịch vụ khởi động (khoảng 30-60 giây)..."
echo ""

# Phần 2: Kiểm tra các dịch vụ
echo "=== PHẦN 2: KIỂM TRA CÁC DỊCH VỤ ==="
echo "Kiểm tra trạng thái các container:"
echo "Lệnh: docker-compose ps"
echo ""
echo "Kiểm tra Kafka Connect API:"
echo "Lệnh: curl -s http://localhost:8083/ | jq"
echo ""
echo "Kiểm tra các connector đã cài đặt:"
echo "Lệnh: curl -s http://localhost:8083/connector-plugins | jq"
echo ""

# Phần 3: Phương pháp 1 - Consumer-based Integration (đã triển khai)
echo "=== PHẦN 3: PHƯƠNG PHÁP 1 - CONSUMER-BASED INTEGRATION ==="
echo "Phương pháp này đã được triển khai trong consumer-kafka."
echo "Kiểm tra logs của consumer-kafka:"
echo "Lệnh: docker-compose logs consumer-kafka"
echo ""
echo "Gửi message đến Kafka để kiểm tra:"
echo "Lệnh: curl -X POST http://localhost:3000/kafka/send -H 'Content-Type: application/json' -d '{\"message\": \"Test message for consumer-based integration\"}'"
echo ""
echo "Kiểm tra logs để xác nhận message đã được lưu vào MongoDB:"
echo "Lệnh: docker-compose logs consumer-kafka"
echo ""

# Phần 4: Phương pháp 2 - Kafka Sink Connector
echo "=== PHẦN 4: PHƯƠNG PHÁP 2 - KAFKA SINK CONNECTOR ==="
echo "Triển khai MongoDB Sink Connector để đưa dữ liệu từ Kafka vào MongoDB:"
echo "Lệnh: curl -X POST -H \"Content-Type: application/json\" --data @mongodb-sink-connector.json http://localhost:8083/connectors"
echo ""
echo "Kiểm tra trạng thái của connector:"
echo "Lệnh: curl -s http://localhost:8083/connectors/mongodb-sink-connector/status | jq"
echo ""
echo "Gửi message đến Kafka để kiểm tra Sink Connector:"
echo "Lệnh: curl -X POST http://localhost:3000/kafka/send -H 'Content-Type: application/json' -d '{\"message\": \"Test message for Kafka Sink Connector\"}'"
echo ""
echo "Kiểm tra dữ liệu trong MongoDB (collection: kafka_messages_sink):"
echo "Truy cập MongoDB Express: http://localhost:8081"
echo "Đăng nhập với username: admin, password: pass"
echo "Chọn database 'message_queue_demo' và collection 'kafka_messages_sink'"
echo ""

# Phần 5: Phương pháp 3 - Kafka Source Connector
echo "=== PHẦN 5: PHƯƠNG PHÁP 3 - KAFKA SOURCE CONNECTOR ==="
echo "Tạo collection source_data trong MongoDB:"
echo "Lệnh: docker exec -it mongodb mongosh -u root -p example --eval 'use message_queue_demo; db.createCollection(\"source_data\")'"
echo ""
echo "Triển khai MongoDB Source Connector để đưa dữ liệu từ MongoDB vào Kafka:"
echo "Lệnh: curl -X POST -H \"Content-Type: application/json\" --data @mongodb-source-connector.json http://localhost:8083/connectors"
echo ""
echo "Kiểm tra trạng thái của connector:"
echo "Lệnh: curl -s http://localhost:8083/connectors/mongodb-source-connector/status | jq"
echo ""
echo "Thêm dữ liệu vào MongoDB để kiểm tra Source Connector:"
echo "Lệnh: docker exec -it mongodb mongosh -u root -p example --eval 'use message_queue_demo; db.source_data.insertOne({name: \"Test Document\", value: \"This is a test for Kafka Source Connector\", timestamp: new Date()})'"
echo ""
echo "Kiểm tra message trong Kafka topic 'mongodb.message_queue_demo.source_data':"
echo "Lệnh: docker exec -it kafka kafka-console-consumer --bootstrap-server kafka:29092 --topic mongodb.message_queue_demo.source_data --from-beginning"
echo ""

# Phần 6: So sánh các phương pháp
echo "=== PHẦN 6: SO SÁNH CÁC PHƯƠNG PHÁP ==="
echo "1. Consumer-based Integration:"
echo "   - Ưu điểm: Tùy chỉnh cao, kiểm soát hoàn toàn logic xử lý"
echo "   - Nhược điểm: Phải tự xử lý lỗi, retry, và mở rộng"
echo ""
echo "2. Kafka Sink Connector:"
echo "   - Ưu điểm: Dễ cấu hình, tự động xử lý lỗi, không cần viết code"
echo "   - Nhược điểm: Ít tùy chỉnh hơn về logic xử lý"
echo ""
echo "3. Kafka Source Connector:"
echo "   - Ưu điểm: Tự động đồng bộ dữ liệu từ MongoDB vào Kafka"
echo "   - Nhược điểm: Phức tạp hơn trong việc theo dõi thay đổi"
echo ""

# Phần 7: Dọn dẹp
echo "=== PHẦN 7: DỌN DẸP ==="
echo "Xóa các connector:"
echo "Lệnh: curl -X DELETE http://localhost:8083/connectors/mongodb-sink-connector"
echo "Lệnh: curl -X DELETE http://localhost:8083/connectors/mongodb-source-connector"
echo ""
echo "Dừng và xóa các container:"
echo "Lệnh: docker-compose down"
echo ""

echo "=== KẾT THÚC HƯỚNG DẪN ==="
echo "Bạn có thể chạy từng lệnh trong script này để hiểu rõ từng phương pháp."
